namespace GlobalDomination.GameData
{
    public enum CountryType
    {
        England,
        America,
        France,
        Russia
    }

    public enum BuildingType
    {
        None,
        Barack,
        Machinery,
        MoneyBuilder,
        MutantLaboratory,
        Farm,
        Workshop,
        TrainingGround,
        Hospital,
        Bank,
        Factory,
        Laboratory,
        Mine,
        Port,
        Airport,
        PowerPlant,
        University,
        ResearchCenter,
        Arsenal,
        Fortress,
        TradingPost,
        SpyNetwork,
        CommandCenter,
        RadioStation,
        Bunker,
        MissileBase,
        NuclearReactor,
        SpaceCenter,
        CyberCenter,
        BioWeaponLab,
        CloneFactory,
        TimeVault,
        EnergyShield,
        TeleportGate,
        QuantumComputer,
        ArtificialIntelligence
    }
}
